[project]
name = "tsv-form"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "reportlab>=4.4.7",
    "svglib>=1.6.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
